# Generated by Django 2.2.7 on 2019-11-13 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dogproduct',
            old_name='produt_type',
            new_name='product_type',
        ),
    ]
