# Generated by Django 2.2.7 on 2019-11-15 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191115_1622'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Purchase',
            new_name='DogPurchase',
        ),
    ]
