# Generated by Django 2.2.7 on 2019-11-15 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191115_1721'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DogPurchase',
            new_name='Purchase',
        ),
    ]
